name: Teaching
description: Teaching materials
url: "https://milanxpetrovic.github.io/teaching/"
markdown: gem
compress_html:
  blanklines: false
latex: mathjax
plugins:
- jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red