name: Teaching
description: Teaching materials
url: "https://milanxpetrovic.github.io/teaching/"
markdown: gem
plugins:
- jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
markdown_extensions:
  - callouts
