name: Teaching
description: Teaching materials
url: "https://milanxpetrovic.github.io/teaching/"
markdown: gem
plugins:
- jekyll-remote-theme
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs